// <auto-generated />
using System;
using AuditWorkFlow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditWorkFlow.Api.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20250119111836_seed data1")]
    partial class seeddata1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditWorkFlow.Api.Models.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PanNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33bbc9f2-869d-47a7-8d90-d2b533b60f48"),
                            CountryCode = "+91",
                            Email = "prad@gmail.com",
                            FirstName = "Pradeep",
                            LastName = "Gandham",
                            PanNumber = "testpan001",
                            PhoneNumber = "9292929292"
                        },
                        new
                        {
                            Id = new Guid("f51fdf1b-aee9-441f-9ed5-1877ac407cc9"),
                            CountryCode = "+91",
                            Email = "prav@gmail.com",
                            FirstName = "Praveen",
                            LastName = "Gandham",
                            PanNumber = "testpan002",
                            PhoneNumber = "898989898"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
